### ISSUE TITLE
NameError: name 'Enum' is not defined

### ISSUE THREAD

**Issue by dinatrina** [SoufiyanBAHADI/ALCA#1]
Hi,
I'm simply trying to test your code - I'm getting this:
 
(envPy3.8Sl) ddd@ncl-gpu-04:~/work/ASR/ALCA$ python -m main.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/ddd/work/ASR/ALCA/main.py", line 16, in <module>
    from managers.PlottingManager import PlottingManager
  File "/home/ddd/work/ASR/ALCA/managers/PlottingManager.py", line 13, in <module>
    from constants import FONT_SIZE, FilterBank, Example
  File "/home/ddd/work/ASR/ALCA/constants.py", line 11, in <module>
    class FilterBank(Enum):
NameError: name 'Enum' is not defined

by adding
from enum import Enum
to constants.py

I get over that point but I get this:

(envPy3.8Sl) ddd@ncl-gpu-04:~/work/ASR/ALCA$ python -m main.py
/home/ddd/envPy3.8Sl/bin/python: Error while finding module specification for 'main.py' (ModuleNotFoundError: __path__ attribute not found on 'main' while trying to find 'main.py')

**Comment by SoufiyanBAHADI** [comment]
Hi,

There was a problem with the imports and the command line to run the code.
Could you pull this code version and run it with: python main.py

Thank you for posting the issue.
