### ISSUE TITLE
wrong weights dimensions

### ISSUE THREAD

**Issue by dinatrina** [SoufiyanBAHADI/ALCA#2]
Hi, 
made it to download the database - checking in the paper.
converted the .flac files to .wav
run this into the /audio folder of your dataset:
```
from pydub import AudioSegment
from glob import glob
G = glob("*-english*.flac")
for g in G: AudioSegment.from_file(g).export(g[:-4]+'wav', format = "wav")

```

Now, I got over that point and the is a size mismatch

(envPy3.8Sl) ddd@ncl-gpu-04:~/work/ASR/ALCA$ python -m main
2022-01-31 05:05:48.437846: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
WARNING:tensorflow:From /home/ddd/envPy3.8Sl/lib/python3.8/site-packages/tensorflow/python/summary/summary_iterator.py:68: tf_record_iterator (from tensorflow.python.lib.io.tf_record) is deprecated and will be removed in a future version.
Instructions for updating:
Use eager execution and:
`tf.data.TFRecordDataset(path)`
epoch 0:
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ddd/work/ASR/ALCA/main.py", line 289, in <module>
    main(args)
  File "/home/ddd/work/ASR/ALCA/main.py", line 201, in main
    fit(lca, train_set, test_set, args.eval, args.plot, args.resume)
  File "/home/ddd/work/ASR/ALCA/main.py", line 65, in fit
    loss, act, mse, snr = run(lca, train_set, mode='train')
  File "/home/ddd/work/ASR/ALCA/main.py", line 49, in run
    lca()
  File "/home/ddd/envPy3.8Sl/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ddd/work/ASR/ALCA/net/LcaNet.py", line 78, in forward
    self.weights = self.cm.compute_weights()
  File "/home/ddd/work/ASR/ALCA/managers/ContextManager.py", line 116, in compute_weights
    weights = self.__t**(self.filter_ord - 1) * torch.exp(
  File "/home/ddd/envPy3.8Sl/lib/python3.8/site-packages/torch/_tensor.py", line 30, in wrapped
    return f(*args, **kwargs)
RuntimeError: The size of tensor a (1024) must match the size of tensor b (0) at non-singleton dimension 1

**Comment by SoufiyanBAHADI** [comment]
Hi,

I am not able to reproduce this bug. Could you add these lines at the beginning of the function compute_weights in the file ContextManager.py and run again:

print("__t: ", self.__t.shape)
print("__central_freq: ", self.__central_freq.shape)
print("__bandwidth: ", self.__bandwidth.shape)
print("b: ", self.b.shape)
print("c: ", self.c.shape)
print("filter_ord: ", self.filter_ord.shape)

**Comment by dinatrina** [comment]
2022-02-02 10:30:09.020422: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
WARNING:tensorflow:From /home/ddd/envPy3.8Sl/lib/python3.8/site-packages/tensorflow/python/summary/summary_iterator.py:68: tf_record_iterator (from tensorflow.python.lib.io.tf_record) is deprecated and will be removed in a future version.
Instructions for updating:
Use eager execution and:
`tf.data.TFRecordDataset(path)`
epoch 0:
__t:  torch.Size([16, 1024])
__central_freq:  torch.Size([16, 1])
__bandwidth:  torch.Size([16, 1])
b:  torch.Size([0])
c:  torch.Size([0])
filter_ord:  torch.Size([0])
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ddd/work/ASR/ALCA/main.py", line 289, in <module>
    main(args)
  File "/home/ddd/work/ASR/ALCA/main.py", line 201, in main
    fit(lca, train_set, test_set, args.eval, args.plot, args.resume)
  File "/home/ddd/work/ASR/ALCA/main.py", line 65, in fit
    loss, act, mse, snr = run(lca, train_set, mode='train')
  File "/home/ddd/work/ASR/ALCA/main.py", line 49, in run
    lca()
  File "/home/ddd/envPy3.8Sl/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ddd/work/ASR/ALCA/net/LcaNet.py", line 78, in forward
    self.weights = self.cm.compute_weights()
  File "/home/ddd/work/ASR/ALCA/managers/ContextManager.py", line 122, in compute_weights
    weights = self.__t**(self.filter_ord - 1) * torch.exp(
  File "/home/ddd/envPy3.8Sl/lib/python3.8/site-packages/torch/_tensor.py", line 30, in wrapped
    return f(*args, **kwargs)
RuntimeError: The size of tensor a (1024) must match the size of tensor b (0) at non-singleton dimension 1

**Comment by SoufiyanBAHADI** [comment]
Hi,

Apparently, there was a problem with your version of python and the method for loading parameters from the tf event file that is deprecated.

**Comment by dinatrina** [comment]
mhh... maybe -- although usually "deprecated" doesn't mean that it gives wrong results.
At any rate, would you care sharing your current setup so I can reproduce your results (requirements.txt is clearly not enough)

**Comment by SoufiyanBAHADI** [comment]
Python version is 3.6. But before changing your setup, can you pull and retry ?
